# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: go-hello-service # The name of the service
  namespace: default
spec:
  type: NodePort # Exposes the service on each Node's IP at a static port. Easiest for Minikube.
  selector:
    app: go-hello # This MUST match the 'app' label in the deployment.yaml. This is how the service finds the Pods.
  ports:
    - protocol: TCP
      port: 80       # The port the service will be available on inside the cluster
      targetPort: 8080 # The port on the Pods (our Go app's port) that traffic should be sent to